name: SPX GEX collector

on:
  workflow_dispatch:
  # schedule dodamy później

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          which python
          python -m pip install --upgrade pip
          # zainstaluj wymagania z repo (już bez złej wersji)
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # na wszelki wypadek doinstaluj playwright (gdyby nie było w requirements)
          python -m pip install playwright
          # przeglądarka + zależności systemowe
          python -m playwright install --with-deps chromium

      - name: Run collector
        env:
          GFLOW_URL: https://gflows.up.railway.app
        run: |
          # podmień ścieżkę, jeśli masz inny plik
          python spx_gex_only.py

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spx_gex
          path: data/*.csv
          if-no-files-found: ignore
